### ISSUE TITLE
nothing appened how to debug ?

### ISSUE THREAD

**Issue by badoubadou** [kmturley/wordpress-bitbucket-trigger-pipeline#2]
Hi kmturley,
I'm trying to use your plugin, but after new post update, or new post, nothing append to my bitbucket pipeline. 
I have followed all the steps, but I'm wondering if you're not missing the workspace parameter in the call to the api. 
Is the plugin still working ? Did I missed something ? 
How can I debug what is wrong ?

**Comment by kmturley** [comment]
I believe the Wordpress and Bitbucket apis have both changed since I made this plugin.

You can debug by adding echo statements into the code:

```
function publish_static_hook($id) {
  echo 'publish_static_hook';
  echo $id;
  echo '<pre>https://api.bitbucket.org/2.0/repositories/'.$bitbucket_project.'/pipelines</pre>';
  echo '<pre>'.print_r($data, true).'</pre>';
  echo '<pre>'.print_r($response, true).'</pre>';
}
```

I'm not planning to support this moving forward, but you are welcome to open a PR if you figure out a fix!

**Comment by badoubadou** [comment]
Hi @kmturley, It's very easy to correct. 
`'https://api.bitbucket.org/2.0/repositories/'.$bitbucket_username.'/'.$bitbucket_project.'/`
